<div class="homepage-editor" x-data="{ section: 'hero' }">
    <section class="admin-editor-heading"><div><p class="eyebrow">Website content</p><h1>Edit About page.</h1><p>Manage the complete organisation story, philosophy, approach, imagery and discovery metadata.</p></div><div class="admin-editor-heading-actions"><a href="{{ route('about') }}" target="_blank" rel="noopener noreferrer">Preview About page ↗</a><button type="button" wire:click="save" wire:loading.attr="disabled"><span wire:loading.remove wire:target="save">Save all changes</span><span wire:loading wire:target="save">Saving…</span></button></div></section>
    @if($errors->any())<div class="admin-alert is-error" role="alert">Some fields need attention. Review the editor and save again.</div>@endif

    <div class="homepage-editor-layout">
        <nav class="homepage-editor-nav" aria-label="About page sections">@foreach(['hero' => 'Hero & SEO', 'who' => 'Who we are', 'why' => 'Why we exist', 'problem' => 'The problem', 'philosophy' => 'Philosophy', 'approach' => 'Our approach', 'difference' => 'Our difference', 'closing' => 'Closing message'] as $key => $label)<button type="button" @click="section = '{{ $key }}'; document.getElementById('about-editor-{{ $key }}').scrollIntoView({ behavior: 'smooth' })" :class="{ 'is-active': section === '{{ $key }}' }"><span>{{ str_pad((string) $loop->iteration, 2, '0', STR_PAD_LEFT) }}</span>{{ $label }}</button>@endforeach</nav>
        <form wire:submit="save" class="homepage-editor-form">
            <section id="about-editor-hero" class="editor-section" @mouseenter="section = 'hero'">
                <div class="editor-section-heading"><div><span>01</span><h2>Hero & discovery</h2><p>The page introduction, navigation labels, image and search metadata.</p></div><x-admin-icon name="about" /></div>
                <div class="editor-field-grid"><label class="is-wide">SEO title<input type="text" wire:model="content.meta.title"></label><label class="is-wide">SEO description<textarea rows="3" wire:model="content.meta.description"></textarea></label><label class="is-wide">Eyebrow<input type="text" wire:model="content.hero.eyebrow"></label><label>Headline — first line<input type="text" wire:model="content.hero.title_line_one"></label><label>Headline — second line<input type="text" wire:model="content.hero.title_line_two"></label><label>Highlighted phrase<input type="text" wire:model="content.hero.title_emphasis"></label><label>Button label<input type="text" wire:model="content.hero.button_label"></label><label class="is-wide">Introduction<textarea rows="3" wire:model="content.hero.lead"></textarea></label></div>
                <div class="editor-image-control"><div class="editor-image-preview"><img src="{{ $heroImage?->temporaryUrl() ?? $this->imageUrl($content['hero']['image']) }}" alt="About hero preview"></div><div><h3>About hero image</h3><p>JPG, PNG or WebP, up to 5 MB.</p><label class="editor-file-button">Choose replacement<input type="file" wire:model="heroImage" accept="image/jpeg,image/png,image/webp"></label><div wire:loading wire:target="heroImage" class="editor-uploading">Preparing image…</div>@error('heroImage')<small class="editor-error">{{ $message }}</small>@enderror</div></div>
                <div class="editor-field-grid"><label class="is-wide">Image alternative text<textarea rows="2" wire:model="content.hero.image_alt"></textarea></label><label class="is-wide">Image caption<input type="text" wire:model="content.hero.image_caption"></label></div>
                <h3 class="editor-subheading">On-page navigation</h3><div class="editor-repeat-grid">@foreach($content['contents'] as $index => $label)<label><span>0{{ $index + 1 }}</span><input type="text" wire:model="content.contents.{{ $index }}"></label>@endforeach</div>
            </section>

            @foreach(['who' => ['02', 'Who we are'], 'why' => ['03', 'Why we exist']] as $key => [$number, $heading])
                <section id="about-editor-{{ $key }}" class="editor-section" @mouseenter="section = '{{ $key }}'"><div class="editor-section-heading"><div><span>{{ $number }}</span><h2>{{ $heading }}</h2><p>Edit the complete narrative for this section.</p></div><x-admin-icon :name="$key === 'who' ? 'users' : 'vision'" /></div><div class="editor-field-grid"><label class="is-wide">Section label<input type="text" wire:model="content.{{ $key }}.label"></label><label>Heading<input type="text" wire:model="content.{{ $key }}.title_line_one"></label><label>Highlighted heading<input type="text" wire:model="content.{{ $key }}.title_emphasis"></label><label class="is-wide">Lead paragraph<textarea rows="3" wire:model="content.{{ $key }}.lead"></textarea></label>@foreach($content[$key]['paragraphs'] as $index => $paragraph)<label class="is-wide">Paragraph {{ $index + 1 }}<textarea rows="4" wire:model="content.{{ $key }}.paragraphs.{{ $index }}"></textarea></label>@endforeach @if($key === 'why')<label class="is-wide">Vision and mission link label<input type="text" wire:model="content.why.link_label"></label>@endif</div></section>
            @endforeach

            <section id="about-editor-problem" class="editor-section" @mouseenter="section = 'problem'">
                <div class="editor-section-heading"><div><span>04</span><h2>The problem</h2><p>Edit the leadership gap and its three supporting cards.</p></div><x-admin-icon name="philosophy" /></div>
                <div class="editor-field-grid"><label class="is-wide">Section label<input type="text" wire:model="content.problem.label"></label><label>Heading<input type="text" wire:model="content.problem.title_line_one"></label><label>Highlighted heading<input type="text" wire:model="content.problem.title_emphasis"></label><label class="is-wide">Introduction<textarea rows="3" wire:model="content.problem.introduction"></textarea></label></div>
                <div class="editor-stack">@foreach($content['problem']['cards'] as $index => $card)<fieldset><legend><span>0{{ $index + 1 }}</span>{{ $card['title'] }}</legend><div class="editor-field-grid"><label class="is-wide">Title<input type="text" wire:model="content.problem.cards.{{ $index }}.title"></label><label class="is-wide">Description<textarea rows="4" wire:model="content.problem.cards.{{ $index }}.description"></textarea></label></div></fieldset>@endforeach</div>
            </section>

            <section id="about-editor-philosophy" class="editor-section" @mouseenter="section = 'philosophy'">
                <div class="editor-section-heading"><div><span>05</span><h2>Our philosophy</h2><p>Manage the six principles shown on the About page.</p></div><x-admin-icon name="philosophy" /></div>
                <div class="editor-field-grid"><label class="is-wide">Section label<input type="text" wire:model="content.philosophy.label"></label><label>Heading<input type="text" wire:model="content.philosophy.title_line_one"></label><label>Highlighted heading<input type="text" wire:model="content.philosophy.title_emphasis"></label><label class="is-wide">Introduction<textarea rows="3" wire:model="content.philosophy.introduction"></textarea></label></div>
                <div class="editor-stack">@foreach($content['philosophy']['values'] as $index => $value)<fieldset><legend><span>0{{ $index + 1 }}</span>{{ $value['name'] }}</legend><div class="editor-field-grid"><label class="is-wide">Name<input type="text" wire:model="content.philosophy.values.{{ $index }}.name"></label><label class="is-wide">Description<textarea rows="3" wire:model="content.philosophy.values.{{ $index }}.description"></textarea></label></div></fieldset>@endforeach</div>
            </section>

            <section id="about-editor-approach" class="editor-section" @mouseenter="section = 'approach'">
                <div class="editor-section-heading"><div><span>06</span><h2>Our approach</h2><p>Edit the five-step approach and its supporting image.</p></div><x-admin-icon name="leadership" /></div>
                <div class="editor-field-grid"><label class="is-wide">Section label<input type="text" wire:model="content.approach.label"></label><label>Heading<input type="text" wire:model="content.approach.title_line_one"></label><label>Highlighted heading<input type="text" wire:model="content.approach.title_emphasis"></label><label class="is-wide">Introduction<textarea rows="3" wire:model="content.approach.introduction"></textarea></label></div>
                <div class="editor-image-control"><div class="editor-image-preview"><img src="{{ $approachImage?->temporaryUrl() ?? $this->imageUrl($content['approach']['image']) }}" alt="Approach image preview"></div><div><h3>Approach image</h3><p>JPG, PNG or WebP, up to 5 MB.</p><label class="editor-file-button">Choose replacement<input type="file" wire:model="approachImage" accept="image/jpeg,image/png,image/webp"></label><div wire:loading wire:target="approachImage" class="editor-uploading">Preparing image…</div>@error('approachImage')<small class="editor-error">{{ $message }}</small>@enderror</div></div>
                <div class="editor-field-grid"><label class="is-wide">Image alternative text<textarea rows="2" wire:model="content.approach.image_alt"></textarea></label><label class="is-wide">Image caption<input type="text" wire:model="content.approach.image_caption"></label></div>
                <div class="editor-stack">@foreach($content['approach']['steps'] as $index => $step)<fieldset><legend><span>0{{ $index + 1 }}</span>{{ $step['title'] }}</legend><div class="editor-field-grid"><label class="is-wide">Title<input type="text" wire:model="content.approach.steps.{{ $index }}.title"></label><label class="is-wide">Description<textarea rows="3" wire:model="content.approach.steps.{{ $index }}.description"></textarea></label></div></fieldset>@endforeach</div>
            </section>

            <section id="about-editor-difference" class="editor-section" @mouseenter="section = 'difference'">
                <div class="editor-section-heading"><div><span>07</span><h2>Our difference</h2><p>Manage the four commitments that distinguish the network.</p></div><x-admin-icon name="programmes" /></div>
                <div class="editor-field-grid"><label class="is-wide">Section label<input type="text" wire:model="content.difference.label"></label><label>Heading<input type="text" wire:model="content.difference.title_line_one"></label><label>Highlighted heading<input type="text" wire:model="content.difference.title_emphasis"></label><label class="is-wide">Introduction<textarea rows="3" wire:model="content.difference.introduction"></textarea></label></div>
                <div class="editor-stack">@foreach($content['difference']['cards'] as $index => $card)<fieldset><legend><span>0{{ $index + 1 }}</span>{{ $card['title'] }}</legend><div class="editor-field-grid"><label class="is-wide">Title<input type="text" wire:model="content.difference.cards.{{ $index }}.title"></label><label class="is-wide">Description<textarea rows="4" wire:model="content.difference.cards.{{ $index }}.description"></textarea></label></div></fieldset>@endforeach</div>
            </section>

            <section id="about-editor-closing" class="editor-section" @mouseenter="section = 'closing'"><div class="editor-section-heading"><div><span>08</span><h2>Closing message</h2><p>Edit the final programme invitation.</p></div><x-admin-icon name="external" /></div><div class="editor-field-grid"><label class="is-wide">Eyebrow<input type="text" wire:model="content.closing.eyebrow"></label><label>Heading<input type="text" wire:model="content.closing.title_line_one"></label><label>Highlighted heading<input type="text" wire:model="content.closing.title_emphasis"></label><label class="is-wide">Button label<input type="text" wire:model="content.closing.button_label"></label></div></section>
            <div class="editor-save-bar"><div><strong>Ready to publish?</strong><span>Saving updates the public About page immediately.</span></div><button type="submit" wire:loading.attr="disabled"><span wire:loading.remove wire:target="save">Save all changes</span><span wire:loading wire:target="save">Saving…</span></button></div>
            <div class="editor-danger-zone"><div><strong>Restore original About page</strong><p>This replaces every edited field and removes uploaded About-page images.</p></div><button type="button" wire:click="restoreDefaults" wire:confirm="Restore all original About-page content? This cannot be undone.">Restore defaults</button></div>
        </form>
    </div>
</div>
