<div class="homepage-editor" x-data="{ section: 'hero' }">
    <section class="admin-editor-heading"><div><p class="eyebrow">Programmes & people</p><h1>Edit Leadership.</h1><p>Manage the page introduction, disclosure, leadership groups and individual profiles.</p></div><div class="admin-editor-heading-actions"><a href="{{ route('leadership') }}" target="_blank" rel="noopener noreferrer">Preview leadership ↗</a><button type="button" wire:click="save">Save all changes</button></div></section>
    @if($saved)<div class="admin-alert is-success" role="status" x-data x-init="setTimeout(() => $el.remove(), 4500)">Leadership changes were saved and are now live.</div>@endif
    @if($errors->any())<div class="admin-alert is-error" role="alert">Some fields need attention. Check group IDs are unique, lowercase and hyphenated.</div>@endif
    <div class="homepage-editor-layout"><nav class="homepage-editor-nav" aria-label="Leadership page sections">@foreach(['hero' => 'Hero & SEO', 'notice' => 'Disclosure', 'directory' => 'Directory', 'closing' => 'Closing'] as $key => $label)<button type="button" @click="section = '{{ $key }}'; document.getElementById('leadership-editor-{{ $key }}').scrollIntoView({ behavior: 'smooth' })" :class="{ 'is-active': section === '{{ $key }}' }"><span>0{{ $loop->iteration }}</span>{{ $label }}</button>@endforeach</nav>
        <form wire:submit="save" class="homepage-editor-form">
            <section id="leadership-editor-hero" class="editor-section"><div class="editor-section-heading"><div><span>01</span><h2>Hero & discovery</h2><p>Edit the introduction and search metadata.</p></div><x-admin-icon name="seo" /></div><div class="editor-field-grid"><label class="is-wide">SEO title<input type="text" wire:model="content.meta.title"></label><label class="is-wide">SEO description<textarea rows="3" wire:model="content.meta.description"></textarea></label><label>Eyebrow<input type="text" wire:model="content.hero.eyebrow"></label><label>Action label<input type="text" wire:model="content.hero.action"></label><label class="is-wide">Title<input type="text" wire:model="content.hero.title"></label><label class="is-wide">Description<textarea rows="3" wire:model="content.hero.description"></textarea></label></div></section>
            <section id="leadership-editor-notice" class="editor-section"><div class="editor-section-heading"><div><span>02</span><h2>Directory disclosure</h2><p>Keep visitors informed when profiles are illustrative or unconfirmed.</p></div><x-admin-icon name="about" /></div><div class="editor-field-grid"><label class="is-wide">Notice title<input type="text" wire:model="content.notice.title"></label><label class="is-wide">Notice text<textarea rows="3" wire:model="content.notice.text"></textarea></label><label>Profile label<input type="text" wire:model="content.directory.sample_label"></label><label>Empty group label<input type="text" wire:model="content.directory.empty_label"></label><label class="is-wide">Empty group message<textarea rows="2" wire:model="content.directory.empty_text"></textarea></label></div></section>
            <section id="leadership-editor-directory" class="editor-section"><div class="editor-section-heading"><div><span>03</span><h2>Leadership directory</h2><p>Add, remove and edit groups and profiles. Changes publish immediately when saved.</p></div><x-admin-icon name="leadership" /></div><div class="editor-field-grid"><label class="is-wide">Section label<input type="text" wire:model="content.directory.label"></label></div><div class="editor-stack">
                @foreach($content['directory']['groups'] as $groupIndex => $group)
                    <fieldset wire:key="leadership-group-{{ $groupIndex }}"><legend><span>{{ str_pad((string) ($groupIndex + 1), 2, '0', STR_PAD_LEFT) }}</span>{{ $group['title'] }}</legend><div class="editor-field-grid"><label>Group title<input type="text" wire:model="content.directory.groups.{{ $groupIndex }}.title"></label><label>Anchor ID<input type="text" wire:model="content.directory.groups.{{ $groupIndex }}.id"></label><label>Icon name<input type="text" wire:model="content.directory.groups.{{ $groupIndex }}.icon"></label><label class="is-wide">Description<textarea rows="3" wire:model="content.directory.groups.{{ $groupIndex }}.description"></textarea></label></div>
                        @foreach($group['people'] as $personIndex => $person)
                            <div class="editor-nested-card" wire:key="leadership-person-{{ $groupIndex }}-{{ $personIndex }}"><div class="editor-section-heading"><div><span>PROFILE {{ $personIndex + 1 }}</span><h3>{{ $person['name'] }}</h3></div><button type="button" class="button button-outline" wire:click="removePerson({{ $groupIndex }}, {{ $personIndex }})">Remove profile</button></div><div class="editor-field-grid"><label>Full name<input type="text" wire:model="content.directory.groups.{{ $groupIndex }}.people.{{ $personIndex }}.name"></label><label>Initials fallback<input type="text" wire:model="content.directory.groups.{{ $groupIndex }}.people.{{ $personIndex }}.initials"></label><label>Role<input type="text" wire:model="content.directory.groups.{{ $groupIndex }}.people.{{ $personIndex }}.role"></label><label>Profile label<input type="text" wire:model="content.directory.groups.{{ $groupIndex }}.people.{{ $personIndex }}.profile_label"></label><label class="is-wide">Biography<textarea rows="4" wire:model="content.directory.groups.{{ $groupIndex }}.people.{{ $personIndex }}.bio"></textarea></label></div><div class="editor-image-control profile-image-control"><div class="editor-image-preview is-portrait">@if($profileImages[$groupIndex][$personIndex] ?? null)<img src="{{ $profileImages[$groupIndex][$personIndex]->temporaryUrl() }}" alt="New portrait preview">@elseif($person['photo'] ?? null)<img src="{{ $this->imageUrl($person['photo']) }}" alt="Current portrait preview">@else<div class="profile-initials-preview" aria-hidden="true">{{ $person['initials'] }}</div>@endif</div><div><h3>Profile picture</h3><p>Optional. Without a picture, the public profile displays these initials: <strong>{{ $person['initials'] }}</strong>.</p><label class="editor-file-button">Choose picture<input type="file" wire:model="profileImages.{{ $groupIndex }}.{{ $personIndex }}" accept="image/jpeg,image/png,image/webp"></label>@if(($person['photo'] ?? null) || ($profileImages[$groupIndex][$personIndex] ?? null))<button type="button" class="editor-remove-button" wire:click="removePhoto({{ $groupIndex }}, {{ $personIndex }})">Use initials instead</button>@endif<div wire:loading wire:target="profileImages.{{ $groupIndex }}.{{ $personIndex }}" class="editor-uploading">Preparing picture…</div>@error('profileImages.'.$groupIndex.'.'.$personIndex)<small class="editor-error">{{ $message }}</small>@enderror</div></div><div class="editor-field-grid"><label class="is-wide">Picture alternative text<input type="text" wire:model="content.directory.groups.{{ $groupIndex }}.people.{{ $personIndex }}.photo_alt" placeholder="Portrait of {{ $person['name'] }}"></label></div></div>
                        @endforeach
                        <div class="admin-editor-heading-actions"><button type="button" wire:click="addPerson({{ $groupIndex }})">Add profile</button>@if(count($content['directory']['groups']) > 1)<button type="button" wire:click="removeGroup({{ $groupIndex }})" wire:confirm="Remove this group and all its profiles?">Remove group</button>@endif</div>
                    </fieldset>
                @endforeach
                <button type="button" class="button button-outline" wire:click="addGroup">Add leadership group</button>
            </div></section>
            <section id="leadership-editor-closing" class="editor-section"><div class="editor-section-heading"><div><span>04</span><h2>Closing invitation</h2><p>Edit the final link to Vision & Mission.</p></div><x-admin-icon name="vision" /></div><div class="editor-field-grid"><label class="is-wide">Eyebrow<input type="text" wire:model="content.closing.eyebrow"></label><label>Heading<input type="text" wire:model="content.closing.title_line_one"></label><label>Highlighted heading<input type="text" wire:model="content.closing.title_emphasis"></label><label>Button label<input type="text" wire:model="content.closing.button_label"></label></div></section>
            <div class="editor-save-bar"><div><strong>Ready to publish?</strong><span>Saving updates the public Leadership page immediately.</span></div><button type="submit">Save all changes</button></div><div class="editor-danger-zone"><div><strong>Restore original Leadership page</strong><p>This replaces every edited field, group and profile.</p></div><button type="button" wire:click="restoreDefaults" wire:confirm="Restore all original Leadership content?">Restore defaults</button></div>
        </form>
    </div>
</div>
