<div class="homepage-editor" x-data="{ section: 'hero' }">
    <section class="admin-editor-heading"><div><p class="eyebrow">Website content</p><h1>Edit Philosophy & Focus Areas.</h1><p>Manage the principles and five areas that guide THE IMPACT’s public contribution.</p></div><div class="admin-editor-heading-actions"><a href="{{ route('about.philosophy-focus') }}" target="_blank" rel="noopener noreferrer">Preview page ↗</a><button type="button" wire:click="save" wire:loading.attr="disabled"><span wire:loading.remove wire:target="save">Save all changes</span><span wire:loading wire:target="save">Saving…</span></button></div></section>
    @if($errors->any())<div class="admin-alert is-error" role="alert">Some fields need attention. Review the editor and save again.</div>@endif
    <div class="homepage-editor-layout">
        <nav class="homepage-editor-nav" aria-label="Philosophy and focus page sections">@foreach(['hero' => 'Hero & SEO', 'philosophy' => 'Philosophy', 'focus' => 'Focus areas', 'closing' => 'Closing message'] as $key => $label)<button type="button" @click="section = '{{ $key }}'; document.getElementById('philosophy-editor-{{ $key }}').scrollIntoView({ behavior: 'smooth' })" :class="{ 'is-active': section === '{{ $key }}' }"><span>0{{ $loop->iteration }}</span>{{ $label }}</button>@endforeach</nav>
        <form wire:submit="save" class="homepage-editor-form">
            <section id="philosophy-editor-hero" class="editor-section" @mouseenter="section = 'hero'"><div class="editor-section-heading"><div><span>01</span><h2>Hero & discovery</h2><p>Edit the page introduction, actions and search metadata.</p></div><x-admin-icon name="seo" /></div><div class="editor-field-grid"><label class="is-wide">SEO title<input type="text" wire:model="content.meta.title"></label><label class="is-wide">SEO description<textarea rows="3" wire:model="content.meta.description"></textarea></label><label class="is-wide">Eyebrow<input type="text" wire:model="content.hero.eyebrow"></label><label class="is-wide">Page title<input type="text" wire:model="content.hero.title"></label><label class="is-wide">Introduction<textarea rows="3" wire:model="content.hero.description"></textarea></label><label>Primary action<input type="text" wire:model="content.hero.primary_action"></label><label>Secondary action<input type="text" wire:model="content.hero.secondary_action"></label></div></section>
            <section id="philosophy-editor-philosophy" class="editor-section" @mouseenter="section = 'philosophy'"><div class="editor-section-heading"><div><span>02</span><h2>Our philosophy</h2><p>Edit all six connected principles.</p></div><x-admin-icon name="philosophy" /></div><div class="editor-field-grid"><label class="is-wide">Section label<input type="text" wire:model="content.philosophy.label"></label><label>Heading<input type="text" wire:model="content.philosophy.title_line_one"></label><label>Highlighted heading<input type="text" wire:model="content.philosophy.title_emphasis"></label><label class="is-wide">Introduction<textarea rows="4" wire:model="content.philosophy.introduction"></textarea></label></div><div class="editor-stack">@foreach($content['philosophy']['values'] as $index => $value)<fieldset><legend><span>0{{ $index + 1 }}</span>{{ $value['name'] }}</legend><div class="editor-field-grid"><label class="is-wide">Name<input type="text" wire:model="content.philosophy.values.{{ $index }}.name"></label><label class="is-wide">Description<textarea rows="4" wire:model="content.philosophy.values.{{ $index }}.description"></textarea></label></div></fieldset>@endforeach</div></section>
            <section id="philosophy-editor-focus" class="editor-section" @mouseenter="section = 'focus'"><div class="editor-section-heading"><div><span>03</span><h2>Focus areas</h2><p>Edit all five areas and their public-purpose framing.</p></div><x-admin-icon name="programmes" /></div><div class="editor-field-grid"><label class="is-wide">Section label<input type="text" wire:model="content.focus.label"></label><label>Heading<input type="text" wire:model="content.focus.title_line_one"></label><label>Highlighted heading<input type="text" wire:model="content.focus.title_emphasis"></label><label class="is-wide">Introduction<textarea rows="4" wire:model="content.focus.introduction"></textarea></label></div><div class="editor-stack">@foreach($content['focus']['areas'] as $index => $area)<fieldset><legend><span>0{{ $index + 1 }}</span>{{ $area['name'] }}</legend><div class="editor-field-grid"><label>Name<input type="text" wire:model="content.focus.areas.{{ $index }}.name"></label><label>Eyebrow<input type="text" wire:model="content.focus.areas.{{ $index }}.eyebrow"></label><label class="is-wide">Title<input type="text" wire:model="content.focus.areas.{{ $index }}.title"></label><label class="is-wide">Description<textarea rows="4" wire:model="content.focus.areas.{{ $index }}.description"></textarea></label></div></fieldset>@endforeach</div></section>
            <section id="philosophy-editor-closing" class="editor-section" @mouseenter="section = 'closing'"><div class="editor-section-heading"><div><span>04</span><h2>Closing message</h2><p>Edit the final invitation into the programmes.</p></div><x-admin-icon name="external" /></div><div class="editor-field-grid"><label class="is-wide">Eyebrow<input type="text" wire:model="content.closing.eyebrow"></label><label>Heading<input type="text" wire:model="content.closing.title_line_one"></label><label>Highlighted heading<input type="text" wire:model="content.closing.title_emphasis"></label><label class="is-wide">Button label<input type="text" wire:model="content.closing.button_label"></label></div></section>
            <div class="editor-save-bar"><div><strong>Ready to publish?</strong><span>Saving updates the public Philosophy & Focus Areas page immediately.</span></div><button type="submit" wire:loading.attr="disabled"><span wire:loading.remove wire:target="save">Save all changes</span><span wire:loading wire:target="save">Saving…</span></button></div>
            <div class="editor-danger-zone"><div><strong>Restore original content</strong><p>This replaces every edited field with the original philosophy and focus areas.</p></div><button type="button" wire:click="restoreDefaults" wire:confirm="Restore all original Philosophy & Focus Areas content? This cannot be undone.">Restore defaults</button></div>
        </form>
    </div>
</div>
