<div class="homepage-editor programme-manager">
    <section class="admin-editor-heading"><div><p class="eyebrow">Programmes & people</p><h1>Manage programmes.</h1><p>Edit the public directory, create programme drafts, and control every published programme detail.</p></div><div class="admin-editor-heading-actions"><a href="{{ route('programmes.index') }}" target="_blank" rel="noopener noreferrer">Preview directory ↗</a><button type="button" wire:click="newProgramme">New programme</button></div></section>
    @if($errors->any())<div class="admin-alert is-error" role="alert">Some fields need attention. Review the highlighted programme fields.</div>@endif

    <section class="editor-section"><div class="editor-section-heading"><div><span>01</span><h2>Programme directory page</h2><p>Manage the public listing introduction, preview notice and mentorship callout.</p></div><x-admin-icon name="programmes" /></div>
        <form wire:submit="savePage"><div class="editor-field-grid"><label class="is-wide">SEO title<input type="text" wire:model="pageContent.meta.title"></label><label class="is-wide">SEO description<textarea rows="3" wire:model="pageContent.meta.description"></textarea></label><label>Hero eyebrow<input type="text" wire:model="pageContent.hero.eyebrow"></label><label>Hero button<input type="text" wire:model="pageContent.hero.button_label"></label><label class="is-wide">Hero title<input type="text" wire:model="pageContent.hero.title"></label><label class="is-wide">Hero description<textarea rows="3" wire:model="pageContent.hero.description"></textarea></label><label>Directory label<input type="text" wire:model="pageContent.directory.label"></label><label>Card action<input type="text" wire:model="pageContent.directory.card_action"></label><label>Directory heading<input type="text" wire:model="pageContent.directory.title_line_one"></label><label>Highlighted heading<input type="text" wire:model="pageContent.directory.title_emphasis"></label><label class="is-wide">Directory introduction<textarea rows="3" wire:model="pageContent.directory.introduction"></textarea></label><label>Notice title<input type="text" wire:model="pageContent.directory.notice_title"></label><label class="is-wide">Notice text<textarea rows="3" wire:model="pageContent.directory.notice_text"></textarea></label><label>Mentorship label<input type="text" wire:model="pageContent.mentorship.label"></label><label>Mentorship button<input type="text" wire:model="pageContent.mentorship.button_label"></label><label>Mentorship heading<input type="text" wire:model="pageContent.mentorship.title_line_one"></label><label>Highlighted heading<input type="text" wire:model="pageContent.mentorship.title_emphasis"></label><label class="is-wide">Mentorship lead<textarea rows="3" wire:model="pageContent.mentorship.lead"></textarea></label><label class="is-wide">Mentorship description<textarea rows="3" wire:model="pageContent.mentorship.description"></textarea></label></div><div class="editor-inline-actions"><button type="submit">Save directory page</button><button type="button" class="is-secondary" wire:click="restorePageDefaults" wire:confirm="Restore the original programme-directory content?">Restore page defaults</button></div></form>
    </section>

    <div class="programme-manager-layout">
        <aside class="programme-admin-list"><div><p class="eyebrow">Catalogue</p><strong>{{ $this->programmes->count() }} programmes</strong></div><button type="button" class="programme-new-button" wire:click="newProgramme">＋ New draft</button>@foreach($this->programmes as $item)<button type="button" wire:key="programme-list-{{ $item->id }}" wire:click="selectProgramme({{ $item->id }})" @class(['is-active' => $programmeId === $item->id])><span><strong>{{ $item->name }}</strong><small>{{ $item->status }} · /{{ $item->slug }}</small></span><span aria-hidden="true">→</span></button>@endforeach</aside>

        <form wire:submit="saveProgramme" class="homepage-editor-form">
            <section class="editor-section"><div class="editor-section-heading"><div><span>02</span><h2>{{ $programmeId ? 'Edit programme' : 'Create programme' }}</h2><p>Drafts stay private. Publish only when the information is ready for visitors.</p></div><span class="status-pill">{{ ucfirst($programme['status']) }}</span></div>
                <div class="editor-field-grid"><label>Name<input type="text" wire:model="programme.name"></label><label>Slug<input type="text" wire:model="programme.slug" placeholder="lowercase-kebab-case"></label><label>Category<input type="text" wire:model="programme.category"></label><label>Icon name<input type="text" wire:model="programme.icon"></label><label>Status<select wire:model="programme.status"><option value="draft">Draft — private</option><option value="published">Published — public</option></select></label><label>Display order<input type="number" min="0" wire:model="programme.sort_order"></label><label class="is-wide">Headline<input type="text" wire:model="programme.headline"></label><label class="is-wide">Card summary<textarea rows="3" wire:model="programme.summary"></textarea></label><label class="is-wide">Overview<textarea rows="6" wire:model="programme.overview"></textarea></label><label class="is-wide">Who it is for<textarea rows="4" wire:model="programme.audience"></textarea></label><label>Duration<input type="text" wire:model="programme.duration"></label><label>Registration URL<input type="url" wire:model="programme.registration_url" placeholder="https://…"></label></div>
            </section>

            <section class="editor-section"><div class="editor-section-heading"><div><span>03</span><h2>Learning objectives</h2><p>Describe what participants will work towards.</p></div><button type="button" class="editor-add-button" wire:click="addObjective">＋ Add objective</button></div><div class="editor-stack">@foreach($programme['objectives'] as $index => $objective)<fieldset wire:key="objective-{{ $index }}"><legend><span>0{{ $index + 1 }}</span>Objective</legend><div class="editor-repeat-row"><textarea rows="3" wire:model="programme.objectives.{{ $index }}"></textarea>@if(count($programme['objectives']) > 1)<button type="button" wire:click="removeObjective({{ $index }})">Remove</button>@endif</div></fieldset>@endforeach</div></section>

            <section class="editor-section"><div class="editor-section-heading"><div><span>04</span><h2>Curriculum</h2><p>Build the programme’s connected learning journey.</p></div><button type="button" class="editor-add-button" wire:click="addCurriculum">＋ Add module</button></div><div class="editor-stack">@foreach($programme['curriculum'] as $index => $module)<fieldset wire:key="curriculum-{{ $index }}"><legend><span>0{{ $index + 1 }}</span>{{ $module['title'] ?: 'New module' }}</legend><div class="editor-field-grid"><label class="is-wide">Module title<input type="text" wire:model="programme.curriculum.{{ $index }}.title"></label><label class="is-wide">Description<textarea rows="4" wire:model="programme.curriculum.{{ $index }}.description"></textarea></label></div>@if(count($programme['curriculum']) > 1)<button type="button" class="editor-remove-button" wire:click="removeCurriculum({{ $index }})">Remove module</button>@endif</fieldset>@endforeach</div></section>

            <section class="editor-section"><div class="editor-section-heading"><div><span>05</span><h2>Facilitators</h2><p>Leave empty until confirmed; sample profiles remain clearly labelled.</p></div><button type="button" class="editor-add-button" wire:click="addFacilitator">＋ Add facilitator</button></div><div class="editor-stack">@forelse($programme['facilitators'] as $index => $facilitator)<fieldset wire:key="facilitator-{{ $index }}"><legend><span>0{{ $index + 1 }}</span>{{ $facilitator['name'] ?: 'New facilitator' }}</legend><div class="editor-field-grid"><label>Name<input type="text" wire:model="programme.facilitators.{{ $index }}.name"></label><label>Role<input type="text" wire:model="programme.facilitators.{{ $index }}.role"></label></div><button type="button" class="editor-remove-button" wire:click="removeFacilitator({{ $index }})">Remove facilitator</button></fieldset>@empty<div class="admin-empty-state">No facilitators added.</div>@endforelse</div></section>

            <section class="editor-section"><div class="editor-section-heading"><div><span>06</span><h2>Cohorts & registration</h2><p>Publish only confirmed schedules and use the registration URL when applications open.</p></div><button type="button" class="editor-add-button" wire:click="addCohort">＋ Add cohort</button></div><div class="editor-stack">@forelse($programme['cohorts'] as $index => $cohort)<fieldset wire:key="cohort-{{ $index }}"><legend><span>0{{ $index + 1 }}</span>{{ $cohort['name'] ?: 'New cohort' }}</legend><div class="editor-field-grid"><label class="is-wide">Cohort name<input type="text" wire:model="programme.cohorts.{{ $index }}.name"></label><label>Starts<input type="text" wire:model="programme.cohorts.{{ $index }}.starts"></label><label>Format<input type="text" wire:model="programme.cohorts.{{ $index }}.format"></label><label class="is-wide">Location<input type="text" wire:model="programme.cohorts.{{ $index }}.location"></label></div><button type="button" class="editor-remove-button" wire:click="removeCohort({{ $index }})">Remove cohort</button></fieldset>@empty<div class="admin-empty-state">No cohorts added.</div>@endforelse</div></section>

            <div class="editor-save-bar"><div><strong>{{ $programmeId ? 'Ready to save?' : 'Create this draft?' }}</strong><span>Published programmes update the public catalogue immediately.</span></div><button type="submit" wire:loading.attr="disabled"><span wire:loading.remove wire:target="saveProgramme">{{ $programmeId ? 'Save programme' : 'Create programme' }}</span><span wire:loading wire:target="saveProgramme">Saving…</span></button></div>
            @if($programmeId)<div class="editor-danger-zone"><div><strong>Delete this programme</strong><p>This permanently removes the programme from the dashboard and public website.</p></div><button type="button" wire:click="deleteProgramme" wire:confirm="Permanently delete this programme? This cannot be undone.">Delete programme</button></div>@endif
        </form>
    </div>
</div>
