<div class="homepage-editor" x-data="{ section: 'hero' }">
    <section class="admin-editor-heading"><div><p class="eyebrow">Website content</p><h1>Edit Vision & Mission.</h1><p>Manage the organisation’s vision, mission pathway, philosophy and search metadata.</p></div><div class="admin-editor-heading-actions"><a href="{{ route('about.vision-mission') }}" target="_blank" rel="noopener noreferrer">Preview page ↗</a><button type="button" wire:click="save" wire:loading.attr="disabled"><span wire:loading.remove wire:target="save">Save all changes</span><span wire:loading wire:target="save">Saving…</span></button></div></section>
    @if($errors->any())<div class="admin-alert is-error" role="alert">Some fields need attention. Review the editor and save again.</div>@endif
    <div class="homepage-editor-layout">
        <nav class="homepage-editor-nav" aria-label="Vision and mission page sections">@foreach(['hero' => 'Hero & SEO', 'vision' => 'Vision', 'mission' => 'Mission', 'philosophy' => 'Philosophy', 'closing' => 'Closing message'] as $key => $label)<button type="button" @click="section = '{{ $key }}'; document.getElementById('vision-editor-{{ $key }}').scrollIntoView({ behavior: 'smooth' })" :class="{ 'is-active': section === '{{ $key }}' }"><span>0{{ $loop->iteration }}</span>{{ $label }}</button>@endforeach</nav>
        <form wire:submit="save" class="homepage-editor-form">
            <section id="vision-editor-hero" class="editor-section" @mouseenter="section = 'hero'"><div class="editor-section-heading"><div><span>01</span><h2>Hero & discovery</h2><p>Edit the page introduction, actions and search metadata.</p></div><x-admin-icon name="seo" /></div><div class="editor-field-grid"><label class="is-wide">SEO title<input type="text" wire:model="content.meta.title"></label><label class="is-wide">SEO description<textarea rows="3" wire:model="content.meta.description"></textarea></label><label class="is-wide">Eyebrow<input type="text" wire:model="content.hero.eyebrow"></label><label class="is-wide">Page title<input type="text" wire:model="content.hero.title"></label><label class="is-wide">Introduction<textarea rows="3" wire:model="content.hero.description"></textarea></label><label>Primary action<input type="text" wire:model="content.hero.primary_action"></label><label>Secondary action<input type="text" wire:model="content.hero.secondary_action"></label></div></section>
            <section id="vision-editor-vision" class="editor-section" @mouseenter="section = 'vision'"><div class="editor-section-heading"><div><span>02</span><h2>Our vision</h2><p>Define the future THE IMPACT is working towards.</p></div><x-admin-icon name="vision" /></div><div class="editor-field-grid"><label class="is-wide">Section label<input type="text" wire:model="content.vision.label"></label><label>Heading<input type="text" wire:model="content.vision.title_line_one"></label><label>Highlighted heading<input type="text" wire:model="content.vision.title_emphasis"></label><label class="is-wide">Vision statement<textarea rows="5" wire:model="content.vision.statement"></textarea></label><label class="is-wide">Statement caption<input type="text" wire:model="content.vision.caption"></label></div></section>
            <section id="vision-editor-mission" class="editor-section" @mouseenter="section = 'mission'"><div class="editor-section-heading"><div><span>03</span><h2>Our mission</h2><p>Edit the mission statement and five-stage pathway.</p></div><x-admin-icon name="leadership" /></div><div class="editor-field-grid"><label class="is-wide">Section label<input type="text" wire:model="content.mission.label"></label><label>Heading<input type="text" wire:model="content.mission.title_line_one"></label><label>Highlighted heading<input type="text" wire:model="content.mission.title_emphasis"></label><label class="is-wide">Mission statement<textarea rows="5" wire:model="content.mission.statement"></textarea></label></div><div class="editor-stack">@foreach($content['mission']['steps'] as $index => $step)<fieldset><legend><span>0{{ $index + 1 }}</span>{{ $step['name'] }}</legend><div class="editor-field-grid"><label class="is-wide">Name<input type="text" wire:model="content.mission.steps.{{ $index }}.name"></label><label class="is-wide">Description<textarea rows="4" wire:model="content.mission.steps.{{ $index }}.description"></textarea></label></div></fieldset>@endforeach</div></section>
            <section id="vision-editor-philosophy" class="editor-section" @mouseenter="section = 'philosophy'"><div class="editor-section-heading"><div><span>04</span><h2>Six-part philosophy</h2><p>Manage the principles that guide the mission.</p></div><x-admin-icon name="philosophy" /></div><div class="editor-field-grid"><label class="is-wide">Section label<input type="text" wire:model="content.philosophy.label"></label><label>Heading<input type="text" wire:model="content.philosophy.title_line_one"></label><label>Highlighted heading<input type="text" wire:model="content.philosophy.title_emphasis"></label><label class="is-wide">Introduction<textarea rows="4" wire:model="content.philosophy.introduction"></textarea></label></div><div class="editor-stack">@foreach($content['philosophy']['values'] as $index => $value)<fieldset><legend><span>0{{ $index + 1 }}</span>{{ $value['name'] }}</legend><div class="editor-field-grid"><label class="is-wide">Name<input type="text" wire:model="content.philosophy.values.{{ $index }}.name"></label><label class="is-wide">Description<textarea rows="4" wire:model="content.philosophy.values.{{ $index }}.description"></textarea></label></div></fieldset>@endforeach</div></section>
            <section id="vision-editor-closing" class="editor-section" @mouseenter="section = 'closing'"><div class="editor-section-heading"><div><span>05</span><h2>Closing message</h2><p>Edit the final invitation into the programmes.</p></div><x-admin-icon name="external" /></div><div class="editor-field-grid"><label class="is-wide">Eyebrow<input type="text" wire:model="content.closing.eyebrow"></label><label>Heading<input type="text" wire:model="content.closing.title_line_one"></label><label>Highlighted heading<input type="text" wire:model="content.closing.title_emphasis"></label><label class="is-wide">Button label<input type="text" wire:model="content.closing.button_label"></label></div></section>
            <div class="editor-save-bar"><div><strong>Ready to publish?</strong><span>Saving updates the public Vision & Mission page immediately.</span></div><button type="submit" wire:loading.attr="disabled"><span wire:loading.remove wire:target="save">Save all changes</span><span wire:loading wire:target="save">Saving…</span></button></div>
            <div class="editor-danger-zone"><div><strong>Restore original Vision & Mission page</strong><p>This replaces every edited field with the original content.</p></div><button type="button" wire:click="restoreDefaults" wire:confirm="Restore all original Vision & Mission content? This cannot be undone.">Restore defaults</button></div>
        </form>
    </div>
</div>
