<x-public-page>
    <x-page-intro :eyebrow="$content['hero']['eyebrow']" :title="$content['hero']['title']" :description="$content['hero']['description']" icon="mentor">
        <div class="hero-actions"><a href="#become-a-mentor" class="button button-dark">{{ $content['hero']['mentor_action'] }} <span aria-hidden="true">↗</span></a><a href="#join-as-a-mentee" class="underlined-link">{{ $content['hero']['mentee_action'] }} <span aria-hidden="true">↗</span></a></div>
    </x-page-intro>
    <section class="shell section statement-grid"><div><p class="eyebrow section-label">{{ $content['why']['label'] }}</p><h2>{{ $content['why']['title_line_one'] }}<br><em>{{ $content['why']['title_emphasis'] }}</em></h2><figure class="community-visual"><img src="{{ $whyImageUrl }}" sizes="(min-width: 1024px) 44vw, calc(100vw - 40px)" width="1536" height="1024" loading="lazy" decoding="async" alt="{{ $content['why']['image_alt'] }}"><figcaption><x-icon name="connect" /><span>{{ $content['why']['image_caption'] }}</span></figcaption></figure></div><div class="about-prose"><p class="lead">{{ $content['why']['lead'] }}</p>@foreach($content['why']['paragraphs'] as $paragraph)<p>{{ $paragraph }}</p>@endforeach</div></section>
    <section class="about-purpose-section"><div class="shell section"><div class="section-heading"><div><p class="eyebrow section-label">{{ $content['participation']['label'] }}</p><h2>{{ $content['participation']['title_line_one'] }}<br><em>{{ $content['participation']['title_emphasis'] }}</em></h2></div><p>{{ $content['participation']['introduction'] }}</p></div><div class="participation-grid">@foreach($content['participation']['roles'] as $role => $details)<article class="participation-card"><span class="purpose-icon"><x-icon :name="$role === 'mentor' ? 'mentor' : 'growth'" /></span><p class="eyebrow">{{ $details['eyebrow'] }}</p><h3>{{ $details['title'] }}</h3><p>{{ $details['description'] }}</p><ul>@foreach($details['points'] as $point)<li>{{ $point }}</li>@endforeach</ul><a href="{{ $role === 'mentor' ? '#become-a-mentor' : '#join-as-a-mentee' }}" class="underlined-link">{{ $details['link_label'] }} <span aria-hidden="true">↗</span></a></article>@endforeach</div></div></section>
    <section id="matching" class="shell section"><div class="section-heading"><div><p class="eyebrow section-label">{{ $content['matching']['label'] }}</p><h2>{{ $content['matching']['title_line_one'] }}<br><em>{{ $content['matching']['title_emphasis'] }}</em></h2></div><p>{{ $content['matching']['introduction'] }}</p></div><ol class="matching-grid">@foreach($content['matching']['steps'] as $step)<li><span class="purpose-icon"><x-icon :name="$step['icon']" /></span><span class="eyebrow">0{{ $loop->iteration }}</span><h3>{{ $step['title'] }}</h3><p>{{ $step['description'] }}</p></li>@endforeach</ol></section>
    <section class="about-philosophy-section"><div class="shell section"><div class="section-heading"><div><p class="eyebrow section-label">{{ $content['areas']['label'] }}</p><h2>{{ $content['areas']['title_line_one'] }}<br><em>{{ $content['areas']['title_emphasis'] }}</em></h2></div><p>{{ $content['areas']['introduction'] }}</p></div><div class="mentorship-areas">@foreach($programmes as $programme)<div><x-icon :name="$programme->icon" /><span>{{ $programme->name }}</span></div>@endforeach</div></div></section>
    <section class="shell section"><div class="section-heading"><div><p class="eyebrow section-label">{{ $content['take_part']['label'] }}</p><h2>{{ $content['take_part']['title_line_one'] }}<br><em>{{ $content['take_part']['title_emphasis'] }}</em></h2></div><p>{{ $content['take_part']['introduction'] }}</p></div><div class="participation-grid">@foreach($content['take_part']['roles'] as $role => $details)<article id="{{ $role === 'mentor' ? 'become-a-mentor' : 'join-as-a-mentee' }}" class="participation-card"><h3>{{ $details['title'] }}</h3><p>{{ $details['description'] }}</p><p>{{ $details['preparation'] }}</p>@if($details['application_url'])<a class="button button-dark" href="{{ $details['application_url'] }}">{{ $details['title'] }} <span aria-hidden="true">↗</span></a>@endif</article>@endforeach</div></section>
</x-public-page>
