<x-public-page>
    <x-page-intro :eyebrow="$programme['name']" :title="$programme['headline']" :description="$programme['summary']" :icon="$programme['icon']" parent="Programmes" :parent-url="route('programmes.index')"><a href="#registration" class="button button-dark">View registration details <span aria-hidden="true">↓</span></a></x-page-intro>
    <div class="shell preview-notice"><x-icon name="identify" /><p><strong>Illustrative programme.</strong> The curriculum, duration, facilitators and cohort details are sample content. This is not an open application.</p></div>
    <div class="shell programme-detail-grid section">
        <div class="programme-body">
            <section id="overview"><p class="eyebrow section-label">01 / OVERVIEW</p><h2>Purpose behind<br><em>the programme.</em></h2><p>{{ $programme['overview'] }}</p></section>
            <section id="objectives"><p class="eyebrow section-label">02 / OBJECTIVES</p><h2>What you’ll work towards.</h2><ul class="objective-list">@foreach($programme['objectives'] as $objective)<li><x-icon name="growth" /><span>{{ $objective }}</span></li>@endforeach</ul></section>
            <section id="audience"><p class="eyebrow section-label">03 / WHO IT’S FOR</p><h2>Is this your next step?</h2><p>{{ $programme['audience'] }}</p></section>
            <section id="curriculum"><p class="eyebrow section-label">04 / CURRICULUM OUTLINE</p><h2>A connected learning journey.</h2><div class="curriculum-list">@foreach($programme['curriculum'] as $module)<details @if($loop->first) open @endif><summary><span class="eyebrow">0{{ $loop->iteration }}</span>{{ $module['title'] }}<span class="details-indicator" aria-hidden="true">+</span></summary><p>{{ $module['description'] }}</p></details>@endforeach</div></section>
            <section id="facilitators"><p class="eyebrow section-label">05 / FACILITATORS</p><h2>Learning with guidance.</h2>@forelse($programme['facilitators'] as $facilitator)<article class="facilitator-row"><span class="purpose-icon"><x-icon name="mentor" /></span><div><h3>{{ $facilitator['name'] }}</h3><p>{{ $facilitator['role'] }}</p></div></article>@empty<p>Facilitators will be announced with the confirmed programme schedule.</p>@endforelse</section>
            <section id="cohorts"><p class="eyebrow section-label">06 / UPCOMING COHORTS</p><h2>Plan your next step.</h2>@forelse($programme['cohorts'] as $cohort)<article class="cohort-card"><span class="status-pill">Sample schedule</span><h3>{{ $cohort['name'] }}</h3><dl><div><dt>Starts</dt><dd>{{ $cohort['starts'] }}</dd></div><div><dt>Format</dt><dd>{{ $cohort['format'] }}</dd></div><div><dt>Location</dt><dd>{{ $cohort['location'] }}</dd></div></dl></article>@empty<div class="empty-state"><p>No upcoming cohorts have been announced. Dates and participation details will appear here once confirmed.</p></div>@endforelse</section>
        </div>
        <aside class="programme-sidebar" aria-label="Programme at a glance"><div class="programme-summary"><p class="eyebrow section-label">AT A GLANCE</p><h2>{{ $programme['name'] }}</h2><dl><div><dt>Duration</dt><dd>{{ $programme['duration'] ?? 'To be announced' }}</dd></div><div><dt>Focus</dt><dd>{{ $programme['category'] }}</dd></div><div><dt>Registration</dt><dd>{{ $programme['registration_url'] ? 'See application details' : 'Preview only' }}</dd></div></dl><nav aria-label="Programme sections"><a href="#overview">Overview</a><a href="#objectives">Objectives</a><a href="#audience">Who it’s for</a><a href="#curriculum">Curriculum</a><a href="#facilitators">Facilitators</a><a href="#cohorts">Upcoming cohorts</a></nav><div id="registration" class="registration-panel"><h3>Take the next step.</h3>@if($programme['registration_url'])<a href="{{ $programme['registration_url'] }}" class="button button-dark">Register for this programme <span aria-hidden="true">↗</span></a>@else<p>Explore what registration will involve. Sample cohorts are not accepting applications.</p><div x-data><button type="button" class="button button-dark" @click="$refs.registrationDialog.showModal()">Preview registration <span aria-hidden="true">↗</span></button><dialog x-ref="registrationDialog" class="application-dialog" @click="if ($event.target === $el) $el.close()" aria-labelledby="registration-title"><div class="dialog-content"><form method="dialog"><button class="dialog-close" aria-label="Close registration preview">×</button></form><p class="eyebrow section-label">APPLICATION PREVIEW</p><h2 id="registration-title">{{ $programme['name'] }}</h2><p>When registration opens, the application will cover your background, learning goals and availability for the cohort.</p><p>Confirmed dates, participation requirements and any costs will be available before you apply.</p><div class="preview-notice"><p>This preview does not collect personal information or reserve a place.</p></div><form method="dialog"><button class="button button-dark">Back to programme</button></form></div></dialog></div>@endif</div></div></aside>
    </div>
    <section class="shell closing-section"><p class="eyebrow">KEEP EXPLORING</p><h2>More ways<br><em>to prepare.</em></h2><a href="{{ route('programmes.index') }}" class="button button-dark">All programmes <span aria-hidden="true">↗</span></a></section>
</x-public-page>
