<x-public-page>
    <x-page-intro :eyebrow="$content['hero']['eyebrow']" :title="$content['hero']['title']" :description="$content['hero']['description']" icon="faith" parent="About" :parent-url="route('about')">
        <div class="hero-actions"><a href="#vision" class="button button-dark">{{ $content['hero']['primary_action'] }} <span aria-hidden="true">↓</span></a><a href="#philosophy" class="underlined-link">{{ $content['hero']['secondary_action'] }} <span aria-hidden="true">↗</span></a></div>
    </x-page-intro>
    <section id="vision" class="shell section statement-grid"><div><p class="eyebrow section-label">{{ $content['vision']['label'] }}</p><h2>{{ $content['vision']['title_line_one'] }}<br><em>{{ $content['vision']['title_emphasis'] }}</em></h2></div><div class="vision-statement"><x-icon name="compass" /><p>{{ $content['vision']['statement'] }}</p><span class="eyebrow">{{ $content['vision']['caption'] }}</span></div></section>
    <section id="mission" class="about-purpose-section"><div class="shell section"><div class="section-heading"><div><p class="eyebrow section-label">{{ $content['mission']['label'] }}</p><h2>{{ $content['mission']['title_line_one'] }}<br><em>{{ $content['mission']['title_emphasis'] }}</em></h2></div><p>{{ $content['mission']['statement'] }}</p></div><ol class="mission-path">@foreach($content['mission']['steps'] as $step)<li><span class="purpose-icon"><x-icon :name="$step['icon']" /></span><span class="eyebrow">0{{ $loop->iteration }}</span><h3>{{ $step['name'] }}</h3><p>{{ $step['description'] }}</p></li>@endforeach</ol></div></section>
    <section id="philosophy" class="about-philosophy-section"><div class="shell section"><div class="section-heading"><div><p class="eyebrow section-label">{{ $content['philosophy']['label'] }}</p><h2>{{ $content['philosophy']['title_line_one'] }}<br><em>{{ $content['philosophy']['title_emphasis'] }}</em></h2></div><p>{{ $content['philosophy']['introduction'] }}</p></div><ol class="about-values">@foreach($content['philosophy']['values'] as $value)<li><span class="value-index">0{{ $loop->iteration }}</span><div><h3>{{ $value['name'] }}</h3><p>{{ $value['description'] }}</p></div></li>@endforeach</ol></div></section>
    <section class="shell closing-section"><span class="closing-star"><x-icon name="growth" /></span><p class="eyebrow">{{ $content['closing']['eyebrow'] }}</p><h2>{{ $content['closing']['title_line_one'] }}<br><em>{{ $content['closing']['title_emphasis'] }}</em></h2><a href="{{ route('programmes.index') }}" class="button button-dark">{{ $content['closing']['button_label'] }} <span aria-hidden="true">↗</span></a></section>
</x-public-page>
